export enum authorsActionTypes {
  FETCH_LIST_PENDING = 'FETCH_LIST_PENDING',
  FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR = 'FETCH_LIST_ERROR',
  ADD_AUTHOR_PENDING = 'ADD_AUTHOR_PENDING',
  ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS',
  ADD_AUTHOR_ERROR = 'ADD_AUTHOR_ERROR',
  DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS',
}
