export enum userBooksActionTypes {
  FETCH_USER_BOOK_PENDING = 'FETCH_USER_BOOK_PENDING',
  FETCH_USER_BOOK_SUCCESS = 'FETCH_USER_BOOK_SUCCESS',
  FETCH_USER_BOOK_ERROR = 'FETCH_USER_BOOK_ERROR',
  BORROW_BOOK_PENDING = 'BORROW_BOOK_PENDING',
  BORROW_BOOK_SUCCESS = 'BORROW_BOOK_SUCCESS',
  BORROW_BOOK_ERROR = 'BORROW_BOOK_ERROR',
  RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS',
  RETURN_BOOK_ERROR = 'RETURN_BOOK_ERROR',
  DELETE_USER_BOOK_SUCCESS = 'DELETE_USER_BOOK_SUCCESS',
}
