export enum booksActionTypes {
  FETCH_BOOK_LIST_PENDING = 'FETCH_BOOK_LIST_PENDING',
  FETCH_BOOK_LIST_SUCCESS = 'FETCH_BOOK_LIST_SUCCESS',
  FETCH_BOOK_LIST_ERROR = 'FETCH_BOOK_LIST_ERROR',
  ADD_BOOK_PENDING = 'ADD_BOOK_PENDING',
  ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS',
  ADD_BOOK_ERROR = 'ADD_BOOK_ERROR',
  DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS',
  SEARCH_BOOKS = 'SEARCH_BOOKS',
}
