export enum booksActionTypes {
  FETCH_LIST_PENDING = 'FETCH_LIST_PENDING',
  FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR = 'FETCH_LIST_ERROR',
  ADD_BOOK_PENDING = 'ADD_BOOK_PENDING',
  ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS',
  ADD_BOOK_ERROR = 'ADD_BOOK_ERROR',
}