export enum authsActionTypes {
  USER_SIGN_UP_PENDING = 'USER_SIGN_UP_PENDING',
  USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE',
  USER_SIGN_IN = 'USER_SIGN_IN',
  USER_SIGN_IN_ERROR = 'USER_SIGN_IN_ERROR',
  USER_SIGN_OUT = 'USER_SIGN_OUT',
}
