export enum userActionTypes {
  FETCH_LIST_PENDING = 'FETCH_LIST_PENDING',
  FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS',
  FETCH_LIST_ERROR = 'FETCH_LIST_ERROR',
  ADD_USER_PENDING = 'ADD_USER_PENDING',
  ADD_USER_SUCCESS = 'ADD_USER_SUCCESS',
  ADD_USER_ERROR = 'ADD_USER_ERROR',
  DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS',
}
